### ISSUE TITLE
Update in accordance to the Origami v2 component specification

### ISSUE THREAD

**Issue by notlee** [Financial-Times/create-origami-component#220]
https://github.com/Financial-Times/origami/pull/86/

**Comment by JakeChampion** [comment]
This is linked to the [new major for origami-build-tools](https://github.com/Financial-Times/origami-build-tools/pull/935). This needs to be completed before releasing the new version of origami build tools.

**Comment by notlee** [comment]
This is done, pending a non-beta release when we're ready to rollout, so closing this issue
