### ISSUE TITLE
Proposal: end-to-end test via obt

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/create-origami-component#50]
I was thinking, maybe it would be useful for this repo to have a set of end-to-end tests which run all the different possible component create setups (no js/no sass/ both js and sass/etc) and run `obt i && obt d && obt v && obt t` on them to ensure they do create valid components

**Comment by notlee** [comment]
that would be useful to catch issues like these https://github.com/Financial-Times/create-origami-component/pull/52
