### ISSUE TITLE
Some observations from migrating o-stepped-progress

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/create-origami-component#8]
Sorry for the rough note form, just want to get these somewhere readable by others:

  - [ ] The `demosDefaults.template` requirement is not documented (or we couldn't find it)
  - [ ] The `demos[x].data.type` requirement is not documented. This corresponds to the variant name in `demosDefaults.variants`, should we rename?
  - [ ] Should we be more permissive with which props are required in `origami.json`?
    - [x] `demosDefaults.variants`: if this is not set, we could just not include a sidebar?
    - [ ] `demosDefaults.template`: this could default to `demos/src/react-template.js`?
  - [ ] Should variant configs have an optional `label` property for when the auto-label generation doesn't suit our needs? This is just me theorising, but an example we encountered: `step1Label` became `Step1 Label` rather than `Step 1 Label`
  - [ ] Check whether `oat demo --watch` is doing what we want it to. We think it's not compiling Sass. This has been OK while we build React demos, but during heavier component development this may be a pain
  - [ ] We no longer need `props.demo` to be set – the demo data is already stored as `state`. We can also remove from the o-message test
  - [ ] Work out what we do with generated `package.json` if one is created by `oat demo`
  - [ ] Check: do demo datafiles as JSON still work, as well as inline data in `origami.json`?

**Comment by chee** [comment]
no longer relevant
