### ISSUE TITLE
Proposal for repeating groups of fields

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/create-origami-component#9]
We ideally need repeating groups of fields for components like o-stepped-progress, which can have any number of steps. This is a proposed solution. Ignore the naming a _little_ bit, as I think the whole variant manifest could use a bit of name tweaking.

Proposing to introduce a new input type named "group" which looks like this:

```js
{
	"name": "step",
	"inputType": "group",
	"repeat": {
		"min": 2,
		"max": 10,
	},
	"groupConfig": [
		{
			"name": "label",
			"inputType": "text",
			"required": true
		}
		{
			"name": "url",
			"inputType": "url"
		},
		{
			"name": "state",
			"inputType": "select",
			"required": true,
			"options": [
				{
					"name": "none"
				},
				{
					"name": "complete"
				},
				{
					"name": "current"
				},
				{
					"name": "error"
				}
			]
		}
	]
}
```

**Comment by gvonkoss** [comment]
Looks good—how do you see that being laid out in the sidebar?
What would `inputType: group` render?

**Comment by rowanmanning** [comment]
I'm thinking a set of fields (not sure how they'd look, grouped somehow in a fieldset?). By default there would be `min` sets of fields output, with a button beneath them to add more. Once you reach `max`, the button is disabled. Possibly each set of fields should be removable as well?
